### ISSUE TITLE
query_string should work with `Option<Display>`

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#3]
According to the documentation, `EGL_NO_DISPLAY` is the only way to get a list of client extensions:

**Comment by timothee-haudebourg** [comment]
That's true. I'll change that. Here is the link to the relevant doc page for the record: https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglQueryString.xhtml
> If display is EGL_NO_DISPLAY, then the EGL_EXTENSIONS string describes the set of supported client extensions

**Comment by timothee-haudebourg** [comment]
I've just published the new version including this fix.
```
khronos-egl = "2.1.0"
```

**Comment by kvark** [comment]
Isn't this a breaking change?

**Comment by timothee-haudebourg** [comment]
It is indeed a breaking change. However in this case since the API is supposed to strictly follow the Khronos specification, I prefer to yank version 2.0.0 altogether since it failed to do so.

**Comment by kvark** [comment]
For the record, I think this decision was incorrect. It basically broke all the existing users. Generally, you'd only want to fail semver if talking about security fixes, not general API fixes.

**Comment by timothee-haudebourg** [comment]
I'll take that into account for the next releases.
