### ISSUE TITLE
Remove khronos dependency?

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#7]
I filed https://github.com/seankerr/rust-khronos/pull/2 and realized that you could get away without this dependency at all if it's just defining a few types. It's also apparently unmaintained, since there is a PR without comments dated Oct 13th...
Can we stop depending on it, can we avoid dragging libc-0.1 into the dep tree?

**Comment by timothee-haudebourg** [comment]
Yes seankerr has been inactive for a while. In fact, this crate originated as a clone of one of its unmaintained crate. There are a few things that I haven't touched after cloning the crate, including the dependency to `khronos` `libc` and `pkg-config`. I am open to discuss removing them.

I liked the idea of having a separate crate defining common khronos types, but if I understand the issue you filed on rust-khronos, it seems that it has become unnecessary.

**Comment by kvark** [comment]
The fun part is that such a change would (once again) technically (probably?) be a breaking change :/
But we'd pretty much require `libc` to be updated in order to publish the next versions of gfx/wgpu/etc...
So there is a problem here. We'd definitely not want to publish a fork of your crate just for this.

**Comment by timothee-haudebourg** [comment]
Yes it would be a breaking change but I don't really see this as a problem. Having a new major version would the occasion to solve all this kind of problems (including the missing API parts you are mentioning in #9, and removing unnecessary dependencies). In this context, removing the dependency to `khronos` and `libc` is the easy part. I'm a bit more worried about `pkg-config`.

**Comment by timothee-haudebourg** [comment]
> We'd definitely not want to publish a fork of your crate just for this.

You don't need to fork, however if you want to take over the crate I could accept it. As long as it is not abandoned like seankerr/rust-khronos was.

**Comment by kvark** [comment]
I'm afraid there is already too much on my plate. I appreciate all the help and timely support you provide on this crate!

To clarify, "We'd definitely not want to publish a fork of your crate just for this." wasn't meant to be a threat by any means :).

I'm just trying to see the best way we could have something published if it depends on your crate without duplicating `libc`.
If you are open to publishing a version without `khronos`, `libc`, and hopefully `pkg-config`, that would be ideal for us.

**Comment by kvark** [comment]
I take it the last release doesn't include these changes?

**Comment by timothee-haudebourg** [comment]
No not yet. It will probably be published along with the `pkg-config` removal.
