### ISSUE TITLE
Build without requiring EGL on the system

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#8]
I wonder if you could remove the need for pkg-config and the EGL package.
In gfx-rs we briefly used `surfman`, and it also relies on EGL by different means, though it didn't try to link with it at build time.

**Comment by timothee-haudebourg** [comment]
Are you referring to your cross-compilation issue?

As I mentioned in #7 , `pkg-config` is an "historical" dependency and not one of my choices. Although i'm not entirely sure it would be a good idea to remove it.

**Comment by kvark** [comment]
I'm not referring to the cross-compilation, no. I'm talking about the fact that the crate simply fails to build if EGL library is not installed in the system, since it tries to discover it with pkg-config.

**Comment by timothee-haudebourg** [comment]
I'm trying to understand why it has been introduced in the first place...

**Comment by kvark** [comment]
The crate tries to link with libEGL at compile time. It should instead do a dynamic library loading and symbol querying at run time, and it has to handle a case where the target system doesn't even have EGL library. So having `pkg-config` issued at build time (and linking with libEGL) appears to be a serious issue to us.

**Comment by kvark** [comment]
As I'm trying to integrate the latest `wgpu` into Gecko, I'm seeing linking issues that I heavily suspect to be caused by that `pkg-config` logic. Building with disabled dependency on `khronos-egl` works fine, so this appears to be a soft blocker. I can land changes with GL backend (and `khronos-egl`) totally disabled as a workaround.

**Comment by timothee-haudebourg** [comment]
I don't want to completely remove the compile-time linking since it can be useful for some. My plan is to allow the user to choose, using features, what behavior they want. Either compile-time linking, or runtime-time linking probably using `sharedlib` (which would become the default).

**Comment by kvark** [comment]
That sounds wonderful, looking forward to that!

**Comment by kvark** [comment]
Hi! Are you still working on this?

**Comment by timothee-haudebourg** [comment]
I'm working on it right now :)

**Comment by kvark** [comment]
FWIW, we use `libloading` everywhere for dynamic libraries. Recently switched to it for the [bit of x11](https://github.com/gfx-rs/gfx/pull/3535/commits/ddf206e7bbd5c0979f6b757cd548435f7bba5927#diff-3c3708b8ab2a59f5c903de589330d635515c80df4ccc5071e0d2db70a1e77227R30-R38) we need. I hope `khronos-egl` does this similarly: dynamic loading without any extra build deps.

**Comment by timothee-haudebourg** [comment]
I was doing it with `dlopen`, but `libloading` seems more popular indeed. I'll try with that instead.

**Comment by timothee-haudebourg** [comment]
The `master` branch now provides a way to dynamically link with the EGL lib at runtime using the `libloading` crate. You'll need to enable the `dynamic` feature. I've also published it on `crates.io` as the `3.0.0-beta` version so the doc can be accessed (although I'm not sure they generate doc for pre releases). If the doc cannot be accessed, you can take a look at the `README.md` example.

I've tested both static and dynamic linking on my side, but I prefer to wait for your feedback to see if this solves your issues before releasing the actual `3.0.0` version.

**Comment by kvark** [comment]
Did you consider hiding `libloading` as an implementation detail? The `egl::Instance::new_dynamic()` could just load the library inside it.

**Comment by timothee-haudebourg** [comment]
Yes I probably should do that. `Instance::new` allows the user to either pass the library by moving or by reference, but I guess in most case the user will want the library to be owned by the `Instance`.

**Comment by kvark** [comment]
Right, that includes us. There is also a slight problem of naming a type of `Instance` when one needs to store it. Perhaps, there could be a `type DynamicInstance = Instance<Dynamic<libloading::Library>>;` or something like this?

Another problem is that `Dynamic` doesn't implement `fmt::Debug`, so neither does `Instance` now, effectively.

**Comment by kvark** [comment]
Also, we are comfortable working with the github dependency for a few weeks, no problem there.

**Comment by timothee-haudebourg** [comment]
I've added the `fmt::Debug` impls and a `DynamicInstance` type with some helper functions as requested. You can use `egl::DynamicInstance::load()` to try to find and load the `libEGL.so` library. Although I'm not entirely confident `libloading` will be able to find it on every platform (in particular on weird systems such as mine, NixOS, where I have to help it a little).

**Comment by kvark** [comment]
Seems to work so far, thank you!

**Comment by timothee-haudebourg** [comment]
Good news! I'll make a last pass to fix some typos and move to `3.0.0` then.
