### ISSUE TITLE
How to get total number of configurations

### ISSUE THREAD

**Issue by kvark** [timothee-haudebourg/khronos-egl#9]
For `choose_config` there is a corresponding https://docs.rs/khronos-egl/2.1.1/khronos_egl/fn.matching_config_count.html
However, I'm not seeing a correspondent one to `get_configs`. Am I missing it?

**Comment by timothee-haudebourg** [comment]
I don't see it either. Of course you can still get all the configs and read the buffer size afterward, but I'm guessing it is not ideal in your case. If we move to a new major version, I'll need to find some time to go over the api spec and catch all this kind of missing parts we inherited from [seankerr/rust-khronos](https://github.com/seankerr/rust-khronos).

**Comment by kvark** [comment]
This shouldn't require a new version, it's just an extra method that we could add here.

**Comment by timothee-haudebourg** [comment]
I've just published version `2.2.0` with the new `get_config_count` function.
